server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/strawberry-fat/springcloud-config.git
          #uri: git@github.com:strawberry-fat/springcloud-config.git #github仓库地址
          #搜索目录
          search-paths:
            - springcloud-config
        #分支
        label: main


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/