server:
  port: 3344

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
spring:
  application:
    name: cloud-config-center #注册进Eureka的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/strawberry-fat/springcloud-config.git
          #uri: git@github.com:strawberry-fat/springcloud-config.git #github仓库地址
          #搜索目录
          search-paths:
            - springcloud-config
        #分支
        label: main

#RabbitMQ相关设置，15672是Web管理界面的端口，5672是MQ访问的端口
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

#RabbitMQ 相关配置，暴露bus刷新配置的断点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'