server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002
  client:
    #false表示不行服务注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心
    fetch-registry: false
    service-url:
      #设置 Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/