server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route           #路由的ID,没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提交服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提交服务的路由地址，LB代表开启负载均衡
          filters:
          predicates:
            - Path=/payment/get/**    #断言，路由相匹配的进行路由

        - id: payment_route2
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提交服务的路由地址
          #uri: http://localhost:8001
          predicates:
            - Path=/payment/discovery/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #false表示不行服务注册中心注册自己
    register-with-eureka: true
    #false表示自己就是注册中心
    fetch-registry: true
    service-url:
      #设置 Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/