server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001
  client:
    #false表示不行服务注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心
    fetch-registry: false
    service-url:
      #设置 Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    #关闭自我保护机制,保证不可用服务被及时删除
    enable-self-preservation: false
    # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    eviction-interval-timer-in-ms: 2000